# @package _global_

defaults:
  - _self_
  - datamodule: null # choose datamodule with `test_dataloader()` for evaluation
  - model: null
  - callbacks: null
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - experiment: MNIST_SimpleDenseNet/V1.yaml

task_name: "eval"

stage: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: RELATIVE/PATH/TO/CKPT/FROM/ROOT
